repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
-   repo: local
    hooks:
      - id: cargo-fmt
        name: run cargo fmt
        language: system
        entry: cargo fmt
        pass_filenames: false
      - id: cargo-check
        name: run cargo check
        language: system
        entry: cargo check
        pass_filenames: false
